//! Synthetic data to exercise the pipeline; never evidence about a physical robot.
use robotrace_sim::{
    config::load_project,
    experiments::{
        calibration::{apply, simulate},
        metrics::object,
    },
    io::persistence::save_loaded_config,
    json::JsonValue as J,
};
use std::{
    io::Write,
    path::{Path, PathBuf},
};
fn main() -> Result<(), String> {
    let root = PathBuf::from(
        std::env::args()
            .nth(1)
            .ok_or("usage: stage10_fixture NEW_DIR")?,
    );
    std::fs::create_dir(&root).map_err(|e| e.to_string())?;
    let mut datasets = Vec::new();
    for (name, split, pwm) in [
        ("training", "calibration", 0.15),
        ("holdout", "validation", 0.25),
    ] {
        let dir = root.join(name);
        std::fs::create_dir(&dir).unwrap();
        let mut cfg = load_project(Path::new("examples/physics/realistic.rtsim"))
            .map_err(|e| e.to_string())?;
        cfg.project_path = dir.join("project.rtsim");
        cfg.project.robot_path = "robot.json".into();
        cfg.project.track_path = "track.json".into();
        cfg.project.duration_s = 0.02;
        cfg.robot.controller.kp = 0.;
        cfg.robot.controller.ki = 0.;
        cfg.robot.controller.kd = 0.;
        cfg.robot.controller.base_pwm = pwm;
        cfg.track.environment.race_enabled = false;
        cfg.track.environment.stop_on_exit = false;
        save_loaded_config(&cfg)?;
        let mut truth = cfg.clone();
        apply(
            &mut truth,
            &[("motor_torque_scale".into(), 1.1)].into_iter().collect(),
        )?;
        let prediction = simulate(truth, 20000)?;
        let mut csv = std::fs::File::create(dir.join("observations.csv")).unwrap();
        writeln!(
            csv,
            "t_us,x_m,y_m,yaw_rad,vx_body_m_s,battery_voltage_v,battery_current_a,line_visible"
        )
        .unwrap();
        for row in prediction.series.rows {
            writeln!(
                csv,
                "{},{},{},{},{},{},{},{}",
                row.t_us,
                row.values["x_m"],
                row.values["y_m"],
                row.values["yaw_rad"],
                row.values["vx_body_m_s"],
                row.values["battery_voltage_v"],
                row.values["battery_current_a"],
                row.values["line_visible"]
            )
            .unwrap();
        }
        let protocol = object([
            (
                "robot_components",
                J::String("synthetic realistic example".into()),
            ),
            (
                "instrument",
                J::String("SimulationCore, no physical instrument".into()),
            ),
            (
                "instrument_accuracy",
                J::String("not applicable: exact synthetic outputs".into()),
            ),
            ("mounting", J::String("planar simulated".into())),
            ("surface", J::String("stage5 modeled surface".into())),
            ("lighting", J::String("modeled reflectance".into())),
            (
                "temperature",
                J::String("model default; not measured".into()),
            ),
            (
                "battery_state",
                J::String("configured SOC, not measured".into()),
            ),
            ("units", J::String("SI, time us".into())),
            (
                "acquisition_rate",
                J::String("1000 Hz log, 20000 Hz physics".into()),
            ),
            (
                "date",
                J::String("synthetic fixture generated by example".into()),
            ),
            ("operator", J::String("stage10_fixture".into())),
        ]);
        datasets.push(object([
            ("id", J::String(name.into())),
            ("split", J::String(split.into())),
            ("kind", J::String("synthetic".into())),
            ("condition_group", J::String(format!("pwm-{pwm}"))),
            ("csv", J::String(format!("{name}/observations.csv"))),
            ("project", J::String(format!("{name}/project.rtsim"))),
            ("origin_us", J::Number(0.)),
            ("offset_us", J::Number(0.)),
            ("max_gap_us", J::Number(1000.)),
            ("time_basis", J::String("delivery".into())),
            ("protocol", protocol),
        ]));
    }
    let study=object([("schema",J::String("rtsim-study-v1".into())),("preset",J::String("realistic".into())),("duration_us",J::Number(20000.)),("tolerance_basis",J::String("software regression only: 1e-8 m/s synthetic exact-model threshold fixed before holdout evaluation; no physical tolerance claim".into())),("parameters",J::Array(vec![object([("name",J::String("motor_torque_scale".into())),("min",J::Number(0.9)),("max",J::Number(1.1)),("steps",J::Number(3.))])])),("objectives",J::Array(vec![object([("signal",J::String("vx_body_m_s".into())),("unit",J::String("m/s".into())),("scale",J::Number(0.1)),("weight",J::Number(1.)),("max_rms",J::Number(1e-8)),("min_coverage",J::Number(1.))])])),("datasets",J::Array(datasets))]);
    std::fs::write(root.join("study.json"), study.to_json()?).map_err(|e| e.to_string())?;
    println!("Synthetic study: {}", root.join("study.json").display());
    Ok(())
}
